Step2 리뷰요청 드립니다.
next-step/jwp-di pull request #116
Opened 2022-08-31 12:45 UTC by itdar

안녕하세요 성준님! 2단계 리뷰요청 드립니다.
2단계 내용 읽고 추가로 리팩토링 해보았습니다.
 1단계에서 mvc 에 적용은 해두었었는데 다시 보니 controller 외에 service, repository 모든 빈들을
핸들러로 등록하고 있던게 있어서 수정했습니다.
감사합니다!!

2022-08-31 13:37 UTC, gwonsungjun requested changes
안녕하세요! 형진님!
미션 구현 잘해주셨어요!
실제 사용되는 기능에 DI를 적용 해보면 좋을 것 같은데, 해당 작업 후 다시 리뷰 요청 부탁드릴게요 :)

2022-08-31 15:06 UTC, itdar commented
> 안녕하세요! 형진님! 미션 구현 잘해주셨어요! 실제 사용되는 기능에 DI를 적용 해보면 좋을 것 같은데, 해당 작업 후 다시 리뷰 요청 부탁드릴게요 :)

 안녕하세요 성준님!!
엇 저는 처음에 실제 사용되는 기능에 DI 를 적용하는게 AnnotationHandler 에 사용되면 실제 사용되는 컨트롤러의 빈들을 빈팩토리로 바꿔서 적용한다고 생각했었는데.. 혹시 어떤 실제 기능을 말씀하시는지 말씀해주실 수 있을까요? 제가 다른 부분으로 잘못 이해한 것 같습니다 ㅎㅎ;;
@gwonsungjun

2022-08-31 22:04 UTC, gwonsungjun commented
@itdar 안녕하세요!
next 패키지 아래 실제 controller, service, dao 클래스들에 적용해보는걸 말씀드린 것 입니다!

2022-09-01 13:02 UTC, itdar commented
> @itdar 안녕하세요! next 패키지 아래 실제 controller, service, �dao 클래스들에 적용해보는걸 말씀드린 것 입니다!

아 기존에 적용이 되어있는 부분인줄 알았었네요 아이고 ㅎㅎ;;
감사합니다 적용해보았습니다!!

2022-09-01 23:44 UTC, gwonsungjun approved these changes
안녕하세요 형진님!
피드백 반영 잘 해주셨네요!
바로 머지하겠습니다. 🙏

2022-09-01 23:44 UTC, merged