🚀 2단계 - DI 구현(힌트)
next-step/jwp-di pull request #151
Opened 2022-09-26 07:10 UTC by fistkim101

이번 step도 잘 부탁드립니다 :)

2022-09-27 08:38 UTC, liquidjoo requested changes
2단계 구현 잘해주셨어요 👍 
생각해볼만한 코멘트 하나 남겼어요~
확인하고 다시 요청 주세요 🙇

2022-09-27 08:38 UTC, liquidjoo commented on src/main/java/core/di/factory/BeanFactory.java
> +        Set<Class<?>> preInstantiatedBeans = beanScanner.scan(basePackage);
Set 을 활용해 중복 제거 👍

2022-09-27 08:38 UTC, liquidjoo commented on src/main/java/core/di/factory/BeanFactory.java
> +            logger.debug("bean created ... class : {}", instantiatedBean.getClass().getName());
빈 생성 시에 순서를 생각해보면 좋을 것 같아요~
MyQnaService 가 빈 등록이 되지 않았는데 QnaController 가 빈으로 등록될 수 있을까요?

<img width="1058" alt="스크린샷 2022-09-27 오후 5 34 00" src="https://user-images.githubusercontent.com/7530347/192476022-d6bf7b2b-610f-409c-b121-6f586464739f.png">

2022-09-27 11:08 UTC, fistkim101 commented on src/main/java/core/di/factory/BeanFactory.java
> +            logger.debug("bean created ... class : {}", instantiatedBean.getClass().getName());
피드백 감사합니다. 수정 반영하였습니다~!

2022-09-28 08:10 UTC, liquidjoo approved these changes
2단계 피드백 반영 정말 좋았습니다 💯 
빈의 생성 순서도 적용하신점 너무 좋네요
다음 단계 진행해 주세요 🙇

2022-09-28 08:10 UTC, merged